"""
Django settings for Ms_Mobile project.

Generated by 'django-admin startproject' using Django 5.2.
"""
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-646kq@s-3l9aupsecwz&73x$fxz52xn&8k97j$7dvv$j)427u#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False


ALLOWED_HOSTS = [
    'ms-mobiles-4us8.onrender.com',
    'localhost',
    '127.0.0.1',
]
# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'mobiles',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'Ms_Mobile.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'Ms_Mobile.wsgi.application'


# Database

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    "site_title": "MS Mobiles Admin",
    "site_header": "MS Mobiles",
    "site_brand": "MS Mobiles",
    "welcome_sign": "Welcome to MS Mobiles Admin",
    "copyright": "MS Mobiles",
    "show_sidebar": True,
    "navigation_expanded": True,
}
# =========================================================
# EMAIL CONFIGURATION - GMAIL
# =========================================================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
# Replace this with your 16-character Gmail App Password
EMAIL_HOST_PASSWORD = 'dpfm bwca lckl zpvf'

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
WHATSAPP_PHONE_NUMBER_ID = "1372955829229389"

WHATSAPP_ACCESS_TOKEN ="EAGUDPh9WnbABSmC7CS1MAPQ1Ezp5m02bu8GzhAZBCDZBMgkYlZAZAXuri62Cnx9YcCxNlBZBu6r99oZBJKZA9kvvXkyRFwtwMsSJtP5Lzur7AePTHvIBavqTASkzXLv7j71A7d2dgdP0j3ZByZC8qXbQUMmvXFrJcVNYEnOSvdF9G8ZABVOORhmCGJP4i8785EoInnnPJ0EXujmE1uNid7f4glbS1xsoQrmjGHgts07tIKZCU8FGk5QmAubp1QQaJFEdGD1KNBLv1V4xnUZCCn7sRnDAVwueVvb80U7idvlmrQZDZD"
